[package]
name = "factory"
description = "Factory Contract Example"
version = "0.1.13"
edition = "2021"
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

# fields to configure build with WASM reproducibility, according to specs  
# in https://github.com/near/NEPs/blob/master/neps/nep-0330.md 
[package.metadata.near.reproducible_build]
# docker image, descriptor of build environment
image = "dj8yfo/sourcescan:0.x.x-dev-git-pull-208"
# tag after colon above serves only descriptive purpose; image is identified by digest
image_digest = "sha256:901cfb2032a1e84d47864bc9609b92bba89f96e25ec6eab2a0e7336a1f876c59"
# build command inside of docker container 
# if docker image from default gallery is used https://hub.docker.com/r/sourcescan/cargo-near/tags,
# the command may be any combination of flags of `cargo-near`,
# supported by respective version of binary inside the container besides `--no-locked` flag
container_build_command = ["cargo", "near", "build", "--no-default-features", "--features", "near-sdk/expensive-debug"]

[build-dependencies]
cargo-near = { version = "0.6.3", git = "https://github.com/dj8yfo/cargo-near.git", branch = "version_mismatch_coerce_warn_fail" }
env_logger = "0.9"
log = "0.4"

[dependencies]
near-sdk = { workspace = true, features = ["unstable"] }

[dev-dependencies]
cargo-near = { version = "0.6.3", git = "https://github.com/dj8yfo/cargo-near.git", branch = "version_mismatch_coerce_warn_fail" }
near-sdk = { workspace = true, features = ["unit-testing"] }
near-workspaces = { version = "0.10.0", features = ["unstable"] }
tokio = { version = "1.12.0", features = ["full"] }
serde_json = "1"
env_logger = "0.9"

