[package]
name = "factory"
description = "Factory Contract Example"
version = "0.1.0"
edition = "2021"
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
cargo-near = { version = "0.6.2", git = "https://github.com/dj8yfo/cargo-near.git", branch = "source-scan-factory-exports" }
tmp_env = "0.1.1"

[dependencies]
near-sdk = { workspace = true, features = ["unstable"] }

[dev-dependencies]
cargo-near = { version = "0.6.2", git = "https://github.com/dj8yfo/cargo-near.git", branch = "source-scan-factory-exports" }
near-sdk = { workspace = true, features = ["unit-testing"] }
near-workspaces = { version = "0.10.0", features = ["unstable"] }
tokio = { version = "1.12.0", features = ["full"] }
serde_json = "1"
env_logger = "0.9"

