[package]
name = "factory"
description = "Factory Contract Example"
version = "0.1.13"
edition = "2021"
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

# fields to configure build with WASM reproducibility, according to specs  
# in https://github.com/near/NEPs/blob/master/neps/nep-0330.md 
# image from sourcescan:latest
# image from cargo-near pull#198
[package.metadata.near.reproducible_build]
# image from cargo-near pull#198
image = "dj8yfo/sourcescan:0.x.x-dev-pr-228"
# tag after colon above serves only descriptive purpose; image is identified by digest
image_digest = "sha256:b93d3b10749ee10b37eabe4823103b8a0e19181386a08fe4f34c8bd2c3c3874e"
# build command inside of docker container 
# if docker image from default gallery is used https://hub.docker.com/r/sourcescan/cargo-near/tags,
# the command may be any combination of flags of `cargo-near`,
# supported by respective version of binary inside the container besides `--no-locked` flag
container_build_command = ["cargo", "near", "build", "--no-default-features", "--features", "near-sdk/expensive-debug"]

[build-dependencies]
env_logger = "0.9"
log = "0.4"

[build-dependencies.cargo-near-build]
version = "0.1.1"
features = ["build_script"]
git = "https://github.com/dj8yfo/cargo-near.git"
branch = "remove_unsafe_std_env_set_var"

[dependencies]
near-sdk = { workspace = true, features = ["unstable"] }

[dev-dependencies.cargo-near-build]
version = "0.1.1"
git = "https://github.com/dj8yfo/cargo-near.git"
branch = "remove_unsafe_std_env_set_var"

[dev-dependencies]
near-sdk = { workspace = true, features = ["unit-testing"] }
near-workspaces = { version = "0.10.0", features = ["unstable"] }
tokio = { version = "1.12.0", features = ["full"] }
serde_json = "1"
env_logger = "0.9"

