[package]
name = "factory"
description = "Factory Contract Example"
version = "0.1.13"
edition = "2021"
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.near.reproducible_build]
image = "dj8yfo/sourcescan:0.x.x-dev-cargo-near-finalization"
image_digest = "sha256:b2257a73041504c203314ede65d25f48cf884acc28610db3b8770e34d4b236d4"
container_build_command = "cargo near build --no-default-features --features near-sdk/expensive-debug"
source_code_git_url = "https://github.com/dj8yfo/factory-rust.git"

[build-dependencies]
cargo-near = { version = "0.6.2", git = "https://github.com/dj8yfo/cargo-near.git", branch = "source-scan-docker-checks2" }
env_logger = "0.9"
log = "0.4"

[dependencies]
near-sdk = { workspace = true, features = ["unstable"] }

[dev-dependencies]
cargo-near = { version = "0.6.2", git = "https://github.com/dj8yfo/cargo-near.git", branch = "source-scan-docker-checks2" }
near-sdk = { workspace = true, features = ["unit-testing"] }
near-workspaces = { version = "0.10.0", features = ["unstable"] }
tokio = { version = "1.12.0", features = ["full"] }
serde_json = "1"
env_logger = "0.9"

