[package]
name = "factory"
description = "Factory Contract Example"
version = "0.1.0"
edition = "2021"
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.near.reproducible_build]
image = "dj8yfo/sourcescan:0.x.x-dev-cargo-near-factory"
image_digest = "sha256:9ef7fd14e7d308b7fbb2dd6471922393b4cae3aa0c1e67c224f6ec910f9faba5"
container_build_command = "cargo near build"
source_code_git_url = "https://github.com/dj8yfo/factory-rust.git"

[build-dependencies]
cargo-near = { version = "0.6.2", git = "https://github.com/dj8yfo/cargo-near.git", branch = "source-scan-factory-exports" }
tmp_env = "0.1.1"

[dependencies]
near-sdk = { workspace = true, features = ["unstable"] }

[dev-dependencies]
cargo-near = { version = "0.6.2", git = "https://github.com/dj8yfo/cargo-near.git", branch = "source-scan-factory-exports" }
near-sdk = { workspace = true, features = ["unit-testing"] }
near-workspaces = { version = "0.10.0", features = ["unstable"] }
tokio = { version = "1.12.0", features = ["full"] }
serde_json = "1"
env_logger = "0.9"

