[package]
name = "donation"
version = "0.1.0"
edition = "2021"
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.near.reproducible_build]
image = "dj8yfo/sourcescan:0.x.x-dev-cargo-near-factory"
image_digest = "sha256:9ef7fd14e7d308b7fbb2dd6471922393b4cae3aa0c1e67c224f6ec910f9faba5"
container_build_command = "cargo near build"
source_code_git_url = "https://github.com/dj8yfo/factory-rust.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
near-sdk = { workspace = true, features = ["legacy"] }

[dev-dependencies]
near-sdk = { workspace = true }
near-workspaces = { version = "0.10.0", features = ["unstable"] }
tokio = { version = "1.12.0", features = ["full"] }
serde_json = "1"
